/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sverm
 */
import javax.swing.*;
import java.awt.*;
import java.sql.*;
public class DepositWithdraw extends javax.swing.JFrame {

    /**
     * Creates new form DepositWithdraw
     */
    public DepositWithdraw() {
        initComponents();
    }

    String userid = MainMenu.userid;   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Deposit = new javax.swing.JRadioButton();
        Withdraw = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup1.add(Deposit);
        Deposit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Deposit.setText("Deposit");
        Deposit.setOpaque(false);
        jPanel1.add(Deposit, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 130, 93, -1));

        buttonGroup1.add(Withdraw);
        Withdraw.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Withdraw.setText("Withdraw");
        Withdraw.setOpaque(false);
        jPanel1.add(Withdraw, new org.netbeans.lib.awtextra.AbsoluteConstraints(513, 130, 100, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Deposit or Withdraw Money");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 34, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Amount");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 254, -1, -1));

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(457, 251, 165, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\sverm\\Pictures\\BankMngmt\\login.png")); // NOI18N
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 438, 93, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\sverm\\Pictures\\BankMngmt\\Close.png")); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(559, 438, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Account Balance");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, -1, 20));

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 330, 160, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\sverm\\Pictures\\BankMngmt\\background.jpg")); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int amount = Integer.parseInt(jTextField1.getText());
        DepoWith dw = new DepoWith();
        int x = dw.ChBal(userid);
        if(Deposit.isSelected()){
            dw.DepoBal(amount, userid);
        }
        else if(Withdraw.isSelected()) {
            if(amount>x) {
                JOptionPane.showMessageDialog(null, "Please enter a valid amount!", "Select", JOptionPane.OK_OPTION);
            }
            else {
                dw.WithBal(amount, userid);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new UserPanel().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        DepoWith dw = new DepoWith();
        int x = dw.ChBal(userid);
        jTextField2.setText(Integer.toString(x));
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DepositWithdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DepositWithdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DepositWithdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DepositWithdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DepositWithdraw().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Deposit;
    private javax.swing.JRadioButton Withdraw;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}


class DepoWith {
    public int ChBal(String userid) {
        int accbal;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bankmngmt","root","121102");
            PreparedStatement st = con.prepareStatement("select accbal from user where userid = ?");
            st.setString(1, userid);
            ResultSet rs = st.executeQuery();
            rs.next();
            accbal = rs.getInt("accbal");   
            st.close();
            con.close();
            return accbal;
        }
        catch(Exception e) {
            System.out.println(e);
        }
        return 0;
    }
    
    public void DepoBal(int amount, String userid){
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bankmngmt","root","121102");
            PreparedStatement st = con.prepareStatement("Update user set accbal = accbal + ? where userid =?");
            st.setInt(1,amount);
            st.setString(2, userid);
            int count = st.executeUpdate();
            if(count==1){
                JOptionPane.showMessageDialog(null, "Amount Deposited: "+amount);
            }
            
            java.util.Date utildate = new java.util.Date();
            java.sql.Date date = new java.sql.Date(utildate.getTime());
            st = con.prepareStatement("Insert into stmt values(?,?,?,?)");
            st.setString(1, userid);
            st.setInt(2, amount);
            st.setString(3, "Deposited");
            st.setDate(4, date);
            st.executeUpdate();
            
            st.close();
            con.close();
        }
        catch(Exception e) {
            System.out.println(e);
        }
    }
    
    public void WithBal(int amount, String userid){
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bankmngmt","root","121102");
            PreparedStatement st = con.prepareStatement("Update user set accbal = accbal - ? where userid = ?");
            st.setInt(1,amount);
            st.setString(2, userid);
            int count = st.executeUpdate();
            if(count==1){
                JOptionPane.showMessageDialog(null, "Amount Withdrawn: "+amount);
            }
            
            java.util.Date utildate = new java.util.Date();
            java.sql.Date date = new java.sql.Date(utildate.getTime());
            st = con.prepareStatement("Insert into stmt values(?,?,?,?)");
            st.setString(1, userid);
            st.setInt(2, amount);
            st.setString(3, "Withdrawn");
            st.setDate(4, date);
            st.executeUpdate();
            
            st.close();
            con.close();
        }
        catch(Exception e) {
            System.out.println(e);
        }
    }
}